---

- name: Fail if running on machines other than RHEL 6/7/8 and CentOS 6/7/8
  fail:
    msg: "This is not a supported system for installation. Must be RHEL 6/7/8 or CentOS 6/7/8."
  when: not (is_rhel_centos_6 or is_rhel_centos_7 or is_rhel_centos_8)

- name: Fail if yum command is not found
  fail:
    msg: "qpc-tools install requires the yum command.  Please install yum and retry."
  when:
    - not install_offline|lower == 'false'
    - not have_yum

- name: Fail if request to use Docker on RHEL 8
  fail:
    msg: "qpc-tools cannot install with Docker on RHEL 8."
  when:
    - is_rhel_centos_8|bool
    - use_docker|bool

- name: Fail if request to use Podman on RHEL 6 or CentOS 6
  fail:
    msg: "qpc-tools cannot install with Podman on RHEL 6 or CentOS 6."
  when:
    - is_rhel_centos_6|bool
    - not use_docker|bool

- name: Create the Quipucords installation directory
  file:
    path: "{{home_dir}}"
    state: directory

- name: Validate Quipucords server version compatibility with RHEL 8
  fail:
    msg: "Quipucords server {{ server_version }} cannot be installed on RHEL 8.  RHEL 8 requires version 0.9.1 or newer."
  when:
  - server_version is defined
  - server_version < '0.9.1'
  - is_rhel_centos_8|bool
