---

- name: Configure the Quipucords CLI to talk to local Quipucords server
  shell: qpc server config --host "{{ server_host }}" --port "{{ server_port }}"
  when:
    - configure_server is defined
    - configure_server|lower == 'true'