---

- name: Set the Quipucords CLI RPM file path
  set_fact:
    qpc_rpm_local_path: "{{ cli_packages }}{{ cli_package_name }}"

- name: Copy offline files to server packages subdirectory
  copy:
    src: "{{offline_files}}/{{cli_package_name}}"
    dest: "{{qpc_rpm_local_path}}"
  ignore_errors: true

- name: Check if the Quipucords CLI RPM file exists
  stat:
    path: "{{ qpc_rpm_local_path }}"
  register: find_qpc_rpm_local

