---

- name: Set the {{home_dir}} CLI subdirectory paths
  set_fact:
    cli_packages: "{{home_dir}}/cli/packages/"

- name: Create the {{home_dir}} CLI subdirectories
  file:
    path: "{{ cli_packages }}"
    state: directory