---

- name: Test for qpc command
  shell: command -v qpc
  register: have_qpc_raw
  ignore_errors: yes

- name: Fail if qpc command was not found
  fail:
    msg: "qpc command not found"
  when:
    - have_qpc_raw.rc != 0
