---

- name: Login to registry with podman
  shell: "podman login -u '{{registry_username}}' -p '{{registry_password}}' '{{registry_url}}'"
  register: registry_login_attempt
  ignore_errors: True
  no_log: True

- fail:
    msg: "Login attempt failed. Log in manually with `podman login {{registry_url}}`"
  when:
    - registry_login_attempt.rc != 0
