---

- name: Login to redhat registry with podman
  shell: "podman login -u '{{rh_registry_username}}' -p '{{rh_registry_password}}' registry.redhat.io"
  register: rh_registry_login_attempt

- name: Debugging
  debug:
    var: rh_registry_login_attempt
