---

- name: Fail if running on machines other than RHEL 6/7/8 and CentOS 6/7/8
  fail:
    msg: "This is not a supported system for installation. Must be RHEL 6/7/8 or CentOS 6/7/8."
  when: not (is_rhel_centos_6 or is_rhel_centos_7 or is_rhel_centos_8)

- name: Fail if yum command is not found
  fail:
    msg: "qpc-tools install requires the yum command.  Please install yum and retry."
  when:
    - not install_offline|lower == 'false'
    - not have_yum

- name: Create the Quipucords installation directory
  file:
    path: "{{home_dir}}"
    state: directory

- name: Validate Quipucords CLI version compatibility with RHEL 8
  fail:
    msg: "Quipucords CLI {{ cli_version }} cannot be installed on RHEL 8.  RHEL 8 requires version 0.9.1 or newer."
  when:
  - cli_version is defined
  - cli_version < '0.9.1'
  - is_rhel_centos_8|bool