---

- name: Setting common default variable values for server installation
  include_role:
    name: server
    tasks_from: init_vars

- name: Validate variable values for server installation
  include_role:
    name: server
    tasks_from: validate_params

- name: Set default values for common variables of online installation for docker and podman)
  include_role:
    name: server
    tasks_from: init_vars_online

- name: Set default values for variables of online installation for docker
  include_role:
    name: server_docker
    tasks_from: init_vars

- name: Remove existing docker containers when they are present
  include_role:
    name: server
    tasks_from: uninstall_docker_containers
  when:
    - have_docker

- name: Remove existing podman containers when they are present
  include_role:
    name: server
    tasks_from: uninstall_podman_containers
  when:
    - have_podman

- name: Install Docker
  include_role:
    name: server_docker
    tasks_from: load_docker_rpm_online

- name: Start Docker service
  include_role:
    name: server_docker
    tasks_from: start_docker_service

- name: Download server image from GitHub
  include_role:
    name: server
    tasks_from: download_quipucords_image_online

- name: Start the PostgreSQL container
  include_role:
    name: server_docker
    tasks_from: start_postgres_container

- name: Start the Quipucords server
  include_role:
    name: server_docker
    tasks_from: start_quipucords_container

- name: Validate that the Quipucords server is up and running
  include_role:
    name: server
    tasks_from: validate_server_install