---

- name: Install the Quipucords components
  hosts: localhost
  vars:
      install_offline: 'false'
      use_supervisord: 'true'
      open_port: 'true'
      server_port: '9443'
      server_name: 'quipucords'
      postgres_version: '9.6.10'
      server_image_name: 'quipucords'
      server_image_tag: ''
      registry_url: 'registry.redhat.io'
      podman_tls_verify: 'true'
      db_name: 'qpc-db'
      server_username: 'admin'
      server_user_email: 'admin@example.com'
      home_dir: "{{ansible_env['HOME'] + '/quipucords'}}"
      server_http_timeout: 120
      db_user: 'postgres'
      use_docker: 'false' # logic elsewhere will change this to docker for RHEL 6
      connect_job_timeout: 600
      inspect_job_timeout: 10800
      ansible_log_level: 0
      have_qpc_docker_containers: false
      have_qpc_podman_containers: false

  tasks:
    - name: Setting default variable values for installation
      include_role:
        name: init
        tasks_from: init_vars

    - name: Validating params for installation
      include_role:
        name: init
        tasks_from: validate_params

    - name: Install the server online using podman
      include_role:
        name: server_podman
        tasks_from: install_online
      when:
        - use_docker|lower == 'false'
        - install_offline|lower == 'false'

    - name: Install the server offline using podman
      include_role:
        name: server_podman
        tasks_from: install_offline
      when:
        - use_docker|lower == 'false'
        - install_offline|lower == 'true'

    - name: Install the server online using docker
      include_role:
        name: server_docker
        tasks_from: install_online
      when:
        - use_docker|lower == 'true'
        - install_offline|lower == 'false'

    - name: Install the server offline using docker
      include_role:
        name: server_docker
        tasks_from: install_offline
      when:
        - use_docker|lower == 'true'
        - install_offline|lower == 'true'
