---

- name: Test for presence of Docker
  shell: command -v docker
  register: have_docker_raw
  ignore_errors: yes

- name: Set variable state indicating presence of Docker
  set_fact:
    have_docker: "{{ have_docker_raw.rc == 0 }}"

- name: Test for podman command
  shell: command -v podman
  register: have_podman_raw
  ignore_errors: yes

- name: Set variable to indicate if Podman command was found
  set_fact:
    have_podman: "{{ have_podman_raw.rc == 0 }}"
  when:
    - have_podman_raw is defined

- name: Defaulting SE Linux Quipucords server installation to false
  set_fact:
    selinux_on: false

- name: Determine if SE Linux is enabled
  shell: selinuxenabled
  register: have_selinux_raw
  ignore_errors: yes

- name: Set variable to use SE Linux sytax when SE Linux is enabled
  set_fact:
    selinux_on: true
  when:
    - have_selinux_raw.rc == 0

- name: Set the {{quipucords_home}} server subdirectory paths
  set_fact:
    server_log_volume: "{{quipucords_home}}/server/volumes/log/"
    server_sshkeys_volume: "{{quipucords_home}}/server/volumes/sshkeys/"
    server_data_volume: "{{quipucords_home}}/server/volumes/data/"
    server_packages: "{{quipucords_home}}/server/packages/"

- name: Create the {{quipucords_home}} server subdirectories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{server_log_volume}}"
    - "{{server_sshkeys_volume}}"
    - "{{server_data_volume}}"
    - "{{server_packages}}"