---

- name: Set the base URL for the Quipucords server container image (user specified version)
  set_fact:
    server_github_release_url: "https://github.com/quipucords/quipucords/releases/download/{{ server_version }}"
  when:
    - not quipucords_image_present
    - server_version is defined

- name: Set the base URL for the Quipucords server container image (latest version)
  set_fact:
    server_github_release_url: "https://github.com/quipucords/quipucords/releases/latest/download"
  when:
    - not quipucords_image_present
    - server_version is not defined

- name: Set Quipucords server container image download URL
  set_fact:
    quipucords_server_container_image_url: "{{ server_github_release_url }}/{{ github_server_filename }}"
  when:
    - not quipucords_image_present

- name: Download Quipucords server container image from GitHub
  get_url:
    url: "{{ quipucords_server_container_image_url }}"
    dest: "{{ server_packages }}"
    tmp_dest: "{{ server_packages }}"
    mode: 0644
    timeout: 300
  when:
    - not quipucords_image_present