---

- name: Set Quipucords server container image file name
  set_fact:
    server_image_filename: "quipucords_server_image.tar.gz"
  when:
    - server_image_filename is not defined

- name: Set Quipucords server container image file path
  set_fact:
    server_image_local_path: "{{ server_packages }}{{ server_image_filename }}"
  when:
    - server_image_local_path is not defined

- name: Set PostgreSQL container image file name
  set_fact:
    postgres_image_filename: "postgres.{{ postgres_version }}.tar"
  when:
    - postgres_image_filename is not defined

- name: Set PostgreSQL container image file path
  set_fact:
    postgres_image_local_path: "{{ server_packages }}{{ postgres_image_filename }}"
  when:
    - postgres_image_local_path is not defined

- name: Copy offline files to server packages subdirectory
  copy:
    src: "{{offline_files}}/{{item.filename}}"
    dest: "{{item.new_dest}}"
  ignore_errors: true
  with_items:
    - {filename: "{{server_image_filename}}", new_dest: "{{server_image_local_path}}"}
    - {filename: "{{postgres_image_filename}}", new_dest: "{{postgres_image_local_path}}"}

- name: Check if Quipucords server container image file exists
  stat:
    path: "{{ server_image_local_path }}"
  register: find_server_image_local

- name: Check if local PostgreSQL container image exists
  stat:
    path: "{{ postgres_image_local_path }}"
  register: find_postgres_image_local
