---

- name: Query GitHub for the latest release of Quipucords server
  uri:
    url: https://github.com/quipucords/quipucords/releases/latest/download/release_info.json
    validate_certs: no
    return_content: yes
  retries: 5
  delay: 5
  register: github_release_response
  until: github_release_response.status == 200 or github_release_response.status == 401
  changed_when: false
  when:
    - server_version is not defined
    - server_image_tag == ""

- name: Load Quipucords server release JSON
  set_fact:
    github_release_info: "{{ github_release_response.content | from_json }}"
  when:
    - server_version is not defined
    - github_release_response is defined
    - github_release_response.content is defined

- name: Parse Quipucords server release version from GitHub release JSON
  set_fact:
    github_release: "{{ github_release_info.version }}"
  when:
    - server_version is not defined
    - github_release_info is defined
    - github_release_info.version is defined

- name: Default the Quipucords server container image tag to the release version when not specified by user
  set_fact:
    server_image_tag: "{{ github_release }}"
  when:
    - server_version is not defined
    - github_release is defined